from PIL import Image, ImageDraw, ImageFont
from enum import Enum

## breaks up the ui into a grid of six boxes that overlap
## either us the two center positions, or the four on the left and right.
## using center and left for example will result in overlap.
class ImagePosition(Enum):
	UPPERLEFT = 1
	UPPERCENTER = 2
	UPPERRIGHT = 3
	LOWERLEFT = 4
	LOWERCENTER = 5
	LOWERRIGHT = 6


class ImageHelper:
	
	def __init__(self, resolution):
		self.resolution = resolution
		
	def load_image(self, path):
		return Image.open(path)
		
	def create_text_image(self, img, text, font_size, position):
		drawing = ImageDraw.Draw(img)
		w, h = drawing.textsize(text, font=self.get_font(font_size))
		box = self.createBoundingBox(position, w, h)
		drawing.text((box[0][0], box[0][1]), text, font=self.get_font(font_size), fill=(255,255,255))
	
	## creates text that goes under a "button", or in our case, 
	## an image generated by create_circle_image
	## pw = parent width
	## ph = parent height
	def create_button_text_image(self, img, text, font_size, pw, ph, position):				
		drawing = ImageDraw.Draw(img)
		coords = self.textPositionForBoundingBox(position, pw, ph)
		drawing.text(coords, text, font=self.get_font(font_size), fill=(255,255,255))

	def create_circle_image(self, img, dia, color, position, outline_color = "black"):
		drawing = ImageDraw.Draw(img)
		bounding_box = self.createBoundingBox(position, dia, dia)
		
		drawing.ellipse(bounding_box, fill = color, outline = outline_color)

	def combine_images(self, img1, img2):
		i1 = img1.convert('RGBA')
		i2 = img2.convert('RGBA')
		return Image.alpha_composite(i1, i2)
	
	def save_image(self, img, filename):
		img.save(img, filename)

	def createBoundingBox(self, position, w, h):
		x = 0
		y = 0
		(xC, yC) = (self.resolution[0] / 2, self.resolution[1] / 2)
		if position == ImagePosition.UPPERLEFT:
			x = (xC / 2) - (w / 2)
			y = yC - h
		if position == ImagePosition.UPPERCENTER: 
			x = xC - (w / 2)
			y = yC - h
		if position == ImagePosition.UPPERRIGHT:
			x = ((xC / 2) + xC) - (w / 2)
			y = yC - h - padding
		if position == ImagePosition.LOWERLEFT:
			x = (xC / 2) - (w / 2)
			y = yC
		if position == ImagePosition.LOWERCENTER:
			x = xC - (w / 2)
			y = yC
		if position == ImagePosition.LOWERRIGHT:
			x = ((xC / 2) + xC) - (w / 2)
			y = yC
			
		if x < 0:
			x = 0
		if y < 0:
			y = 0
			
		return [(x, y), (x+w, y+h)]
		
	def textPositionForBoundingBox(self, position, w, h):
		box = self.createBoundingBox(position, w, h)
		x = box[0][0]
		y = box[1][1]
		return (x, y)
		
	def get_font(self, font_size):
		return ImageFont.truetype('/usr/share/fonts/truetype/piboto/Piboto-Bold.ttf', font_size)
		
